unit dbroot_lite;

interface

// *********************************** 
//   classes for dbroot_lite.proto
//   generated by ProtoBufGenerator 
//        kami-soft 2016-2017
// ***********************************
uses
  System.SysUtils,
  System.Classes,
  System.Generics.Collections,
  pbInput,
  pbOutput,
  pbPublic,
  uAbstractProtoBufClasses;

type
  TEncryptionType=(
    ENCRYPTION_XOR = 0
  );

  TDatabaseVersionProto = class(TAbstractProtoBufClass)
  strict private
    Fquadtree_version: Cardinal;
  strict protected
    function LoadSingleFieldFromBuf(ProtoBuf: TProtoBufInput; FieldNumber: integer; WireType: integer): Boolean; override;
    procedure SaveFieldsToBuf(ProtoBuf: TProtoBufOutput); override;
  public
    constructor Create; override;
    destructor Destroy; override;


    property quadtree_version:Cardinal read Fquadtree_version write Fquadtree_version;
  end;

  TDbRootProto = class(TAbstractProtoBufClass)
  strict private
    Fdatabase_version: TDatabaseVersionProto;
  strict protected
    function LoadSingleFieldFromBuf(ProtoBuf: TProtoBufInput; FieldNumber: integer; WireType: integer): Boolean; override;
    procedure SaveFieldsToBuf(ProtoBuf: TProtoBufOutput); override;
  public
    constructor Create; override;
    destructor Destroy; override;


    property database_version:TDatabaseVersionProto read Fdatabase_version;
  end;

  TEncryptedDbRootProto = class(TAbstractProtoBufClass)
  strict private
    Fencryption_type: TEncryptionType;
    Fencryption_data: TBytes;
    Fdbroot_data: TBytes;
  strict protected
    function LoadSingleFieldFromBuf(ProtoBuf: TProtoBufInput; FieldNumber: integer; WireType: integer): Boolean; override;
    procedure SaveFieldsToBuf(ProtoBuf: TProtoBufOutput); override;
  public

    property encryption_type:TEncryptionType read Fencryption_type write Fencryption_type;
    property encryption_data:TBytes read Fencryption_data write Fencryption_data;
    property dbroot_data:TBytes read Fdbroot_data write Fdbroot_data;
  end;


implementation


constructor TDatabaseVersionProto.Create;
begin
  inherited;
  RegisterRequiredField(1);
end;

destructor TDatabaseVersionProto.Destroy;
begin
  inherited;
end;

function TDatabaseVersionProto.LoadSingleFieldFromBuf(ProtoBuf: TProtoBufInput; FieldNumber: integer; WireType: integer): Boolean;
begin
  Result := inherited LoadSingleFieldFromBuf(ProtoBuf, FieldNumber, WireType);
  if Result then
    exit;
  case fieldNumber of
    1:
      begin
        Fquadtree_version := ProtoBuf.readUInt32;
        Result := True;
      end;
  end;
end;

procedure TDatabaseVersionProto.SaveFieldsToBuf(ProtoBuf: TProtoBufOutput);
begin
  inherited;
  ProtoBuf.writeUInt32(1, Fquadtree_version);
end;


constructor TDbRootProto.Create;
begin
  inherited;
  Fdatabase_version := TDatabaseVersionProto.Create;
end;

destructor TDbRootProto.Destroy;
begin
  Fdatabase_version.Free;
  inherited;
end;

function TDbRootProto.LoadSingleFieldFromBuf(ProtoBuf: TProtoBufInput; FieldNumber: integer; WireType: integer): Boolean;
var
  tmpBuf: TProtoBufInput;
begin
  Result := inherited LoadSingleFieldFromBuf(ProtoBuf, FieldNumber, WireType);
  if Result then
    exit;
  case fieldNumber of
    13:
      begin
        tmpBuf := ProtoBuf.ReadSubProtoBufInput;
        try
          Fdatabase_version.LoadFromBuf(tmpBuf);
        finally
          tmpBuf.Free;
        end;
        Result := True;
      end;
  end;
end;

procedure TDbRootProto.SaveFieldsToBuf(ProtoBuf: TProtoBufOutput);
var
  tmpBuf: TProtoBufOutput;
begin
  inherited;
  tmpBuf:=TProtoBufOutput.Create;
  try
    Fdatabase_version.SaveToBuf(tmpBuf);
    ProtoBuf.writeMessage(13, tmpBuf);
  finally
    tmpBuf.Free;
  end;
end;


function TEncryptedDbRootProto.LoadSingleFieldFromBuf(ProtoBuf: TProtoBufInput; FieldNumber: integer; WireType: integer): Boolean;
begin
  Result := inherited LoadSingleFieldFromBuf(ProtoBuf, FieldNumber, WireType);
  if Result then
    exit;
  case fieldNumber of
    1:
      begin
        Fencryption_type := TEncryptionType(ProtoBuf.readEnum);
        Result := True;
      end;
    2:
      begin
        Fencryption_data := ProtoBuf.readBytes;
        Result := True;
      end;
    3:
      begin
        Fdbroot_data := ProtoBuf.readBytes;
        Result := True;
      end;
  end;
end;

procedure TEncryptedDbRootProto.SaveFieldsToBuf(ProtoBuf: TProtoBufOutput);
begin
  inherited;
  ProtoBuf.writeInt32(1, integer(Fencryption_type));
  ProtoBuf.writeBytes(2, Fencryption_data);
  ProtoBuf.writeBytes(3, Fdbroot_data);
end;

end.
