unit planetoid_metadata;

interface

// *********************************** 
//   classes for planetoid_metadata.proto
//   generated by ProtoBufGenerator 
//        kami-soft 2016-2017
// ***********************************
uses
  System.SysUtils,
  System.Classes,
  System.Generics.Collections,
  pbInput,
  pbOutput,
  pbPublic,
  uAbstractProtoBufClasses;

type
  TEpochInfo = class(TAbstractProtoBufClass)
  strict private
    Ff02: integer;
    Ff05: integer;
  strict protected
    function LoadSingleFieldFromBuf(ProtoBuf: TProtoBufInput; FieldNumber: integer; WireType: integer): Boolean; override;
    procedure SaveFieldsToBuf(ProtoBuf: TProtoBufOutput); override;
  public

    property f02:integer read Ff02 write Ff02;
    property f05:integer read Ff05 write Ff05;
  end;

  TPlanetoidMetadata = class(TAbstractProtoBufClass)
  strict private
    Fepoch: TEpochInfo;
    Fmodel_radius: Single;
  strict protected
    function LoadSingleFieldFromBuf(ProtoBuf: TProtoBufInput; FieldNumber: integer; WireType: integer): Boolean; override;
    procedure SaveFieldsToBuf(ProtoBuf: TProtoBufOutput); override;
  public
    constructor Create; override;
    destructor Destroy; override;


    property epoch:TEpochInfo read Fepoch;
    property model_radius:Single read Fmodel_radius write Fmodel_radius;
  end;


implementation


function TEpochInfo.LoadSingleFieldFromBuf(ProtoBuf: TProtoBufInput; FieldNumber: integer; WireType: integer): Boolean;
begin
  Result := inherited LoadSingleFieldFromBuf(ProtoBuf, FieldNumber, WireType);
  if Result then
    exit;
  case fieldNumber of
    2:
      begin
        Ff02 := ProtoBuf.readInt32;
        Result := True;
      end;
    5:
      begin
        Ff05 := ProtoBuf.readInt32;
        Result := True;
      end;
  end;
end;

procedure TEpochInfo.SaveFieldsToBuf(ProtoBuf: TProtoBufOutput);
begin
  inherited;
  ProtoBuf.writeInt32(2, Ff02);
  ProtoBuf.writeInt32(5, Ff05);
end;


constructor TPlanetoidMetadata.Create;
begin
  inherited;
  Fepoch := TEpochInfo.Create;
end;

destructor TPlanetoidMetadata.Destroy;
begin
  Fepoch.Free;
  inherited;
end;

function TPlanetoidMetadata.LoadSingleFieldFromBuf(ProtoBuf: TProtoBufInput; FieldNumber: integer; WireType: integer): Boolean;
var
  tmpBuf: TProtoBufInput;
begin
  Result := inherited LoadSingleFieldFromBuf(ProtoBuf, FieldNumber, WireType);
  if Result then
    exit;
  case fieldNumber of
    1:
      begin
        tmpBuf := ProtoBuf.ReadSubProtoBufInput;
        try
          Fepoch.LoadFromBuf(tmpBuf);
        finally
          tmpBuf.Free;
        end;
        Result := True;
      end;
    2:
      begin
        Fmodel_radius := ProtoBuf.readFloat;
        Result := True;
      end;
  end;
end;

procedure TPlanetoidMetadata.SaveFieldsToBuf(ProtoBuf: TProtoBufOutput);
var
  tmpBuf: TProtoBufOutput;
begin
  inherited;
  tmpBuf:=TProtoBufOutput.Create;
  try
    Fepoch.SaveToBuf(tmpBuf);
    ProtoBuf.writeMessage(1, tmpBuf);
  finally
    tmpBuf.Free;
  end;
  ProtoBuf.writeFloat(2, Fmodel_radius);
end;

end.
